<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Please fill out the following fields to login:' => 'Будь ласка, коректно заповніть наступні поля для того, щоб авторизуватися',
    'Change E-mail' => 'Змінити е-mail',
    'Change Password' => 'Змінити пароль',
    'Create' => 'Створити',
    'Data was successfully updated' => 'Дані були успішно оновлені',
    'Find' => 'Шукати',
    'Find projects' => 'Пошук проектів',
    'Home' => 'Головна',
    'Login' => 'Вхід',
    'Logout ({email})' => 'Вихід ({email})',
    'N/A' => 'Не вказано',
    'News List' => 'Новини',
    'No' => 'Ні',
    'Page not found' => 'Сторінку не знайдено',
    'Projects' => 'Проекти',
    'Search Result' => 'Рузкльтати пошуку',
    'Select...' => 'Вибрати...',
    'Settings' => 'Налаштування',
    'Subscribe' => 'Підписатись',
    'Topics' => 'Тематики',
    'Unsubscribe' => 'Відписатись',
    'Update' => 'Оновити',
    'Users' => 'Користувачі',
    'Yes' => 'Так',
];
