<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => 'Ви дійсьно хочете видалити цей запис?',
    'Create' => 'Створити',
    'Create News' => 'Створити новину',
    'Created At' => 'Дата створення: ',
    'Delete' => 'Видалити',
    'Description' => 'Опис',
    'ID' => 'ID',
    'News' => 'Новина',
    'Project ID' => 'ID проекту',
    'Title' => 'Заголовок',
    'Update' => 'Оновити',
    'Update {modelClass}: ' => 'Оновити {modelClass}: ',
    'Updated At' => 'Дата оновлення: ',
];
